name: Deploy Code

on:
  push:
    branches:
    - main
    tags:
     - v0.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Get latest push tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
           tag_name: ${{steps.tag.outputs.tag}}
           token: ${{ secrets.GITHUB_TOKEN }}
        
          
          
      
    
