name: Deploy Code

on:
  push:
    branches:
    - main
    tags:
     - v0.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Set env for github tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
           tag_name: ${{ env.RELEASE_VERSION}}
           token: ${{ secrets.GITHUB_TOKEN }}
        
          
          
      
    
