name: Deploy Code

on:
  push:
    branches:
    - main
    tags:
     - v0.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
           tag_name: ${{github.ref_name}}
           token: ${{ secrets.GITHUB_TOKEN }}
        
          
          
      
    
